# Generated by Django 5.2.2 on 2025-06-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
