# Generated by Django 5.2.2 on 2025-06-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_sales", "0002_product_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
