# Generated by Django 5.2.2 on 2025-07-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_sales", "0004_merch"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.ManyToManyField(
                        related_name="author", to="book_sales.product"
                    ),
                ),
            ],
        ),
    ]
