# Generated by Django 5.2.2 on 2025-07-02 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book_sales", "0005_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="author",
            old_name="category",
            new_name="product",
        ),
    ]
