# Generated by Django 5.2.2 on 2025-07-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_sales", "0008_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
