# Generated by Django 5.2.2 on 2025-08-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_sales", "0009_alter_review_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_chat_message", models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name="ChatMessage",
        ),
        migrations.DeleteModel(
            name="Contact",
        ),
    ]
