# Generated by Django 5.2.2 on 2025-08-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_sales", "0010_message_delete_chatmessage_delete_contact"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"permissions": [("can_publish", "Может публиковать статьи")]},
        ),
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
